### ISSUE TITLE
Installation failed on TYPO3 9.5 with composer

### ISSUE THREAD

**Issue by alandolsi** [brainworxx/kreXX-TYPO3-Extension#21]
Uncaught TYPO3 Exception #1476107295: PHP Warning: include(src/Analyse/Callback/AbstractCallback.php): failed to open stream: No such file or directory in /var/www/vhosts/host/httpdocs/public/typo3conf/ext/includekrexx/Resources/Private/krexx/bootstrap.php line 51

in src/Analyse/ the folder names are written in lower case and in krexx/bootstrap.php in upper case:

src/Analyse/callback

include 'src/Analyse/Callback/Analyse/Objects/AbstractObjectAnalysis.php';
include 'src/Analyse/Callback/Analyse/Objects/Constants.php';
include 'src/Analyse/Callback/Analyse/Objects/DebugMethods.php';
include 'src/Analyse/Callback/Analyse/Objects/Getter.php';
include 'src/Analyse/Callback/Analyse/Objects/Methods.php';
include 'src/Analyse/Callback/Analyse/Objects/PrivateProperties.php';
include 'src/Analyse/Callback/Analyse/Objects/ProtectedProperties.php';
include 'src/Analyse/Callback/Analyse/Objects/PublicProperties.php';
include 'src/Analyse/Callback/Analyse/Objects/Traversable.php';

could you solve that please
Thank you

**Comment by guelzow** [comment]
Hi.

At first I would like to thank you for your feedback.

We did have some sort of Git-Corruption with upper-case and lower-case directories, without noticing it.
This [commit](https://github.com/brainworxx/kreXX-TYPO3-Extension/commit/a368333c38b5c6036efa3069c30cb076fc649f84) did fix this, but it's not release-tagged.

The dir `includekrexx/Resources/Private/krexx` is simply a copy-pasta from [this](https://github.com/brainworxx/kreXX/tree/v3.0.1) release. A quick fix would be to simply remove the delete the krexx lib and then upload the one from the link. But that would probably collide with your deployment strategy.

In the meantime, I'll see that I manage to repair the 3.0.1 release here.

Tobi

**Comment by alandolsi** [comment]
Thanks a lot it works!

**Comment by guelzow** [comment]
Glad to hear.
Was just about to test it myself.
