### ISSUE TITLE
TYPO3 10 LTS

### ISSUE THREAD

**Issue by alandolsi** [brainworxx/kreXX-TYPO3-Extension#34]
Support of the new version  10.4 LTS is planned?

**Comment by guelzow** [comment]
The 'lts' is compatible:
https://github.com/brainworxx/kreXX-TYPO3-Extension/tree/v3.3

Today the issue popped up up with some unwanted css interactions with the surrounding site.
I want this one fixed before release.

And I need to test Aimeos v2020.x with our aimeos 'plugin'.
The 2019'er introduced some changes, and I should make sure that both work together (or at least don't produce fatals).

Tobi

**Comment by guelzow** [comment]
We are compatible to TYPO3 10.4 with the 3.3.3 release.
The 10'er badge was not assigned, but nobody got one as far as I can tell.

Tobi
