### ISSUE TITLE
Class 'TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper' not found

### ISSUE THREAD

**Issue by alandolsi** [brainworxx/kreXX-TYPO3-Extension#35]
![image](https://user-images.githubusercontent.com/3594182/84939727-0ff2fe00-b0df-11ea-8f89-c487d621e528.png)

Class 'TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper' not found
TYPO3 Version 10

**Comment by guelzow** [comment]
Strange. That should not have happened.

The class alias map should prevent that. 
Looks like it is not as reliable as I hoped it would be.

Not sure if I can reproduce it, but I think I know how to fix it:
The ViewHelper namespace is declared globally. Letting it point to different PHP namespaces with different ViewHelper classes, depending on the TYPO3 version, should do the trick.

Thanks for reporting.

**Comment by guelzow** [comment]
I was not aware that the class alias map only works with composer if it it explicitly configured in the composer json.
When not working with composer, this configuration is not needed.

Anyway, I've tagged the 3.3.5 release, which should fix this.

**Comment by alandolsi** [comment]
Thank you it works!
